In [1]:
import numpy as np

In [2]:
arr = np.array([3, 8, 2, 9, 5, 7, 1])

In [3]:
arr

array([ 3,  8,  2, 10,  5,  7,  1])

In [5]:
np.where(arr > 5, 0, np.nan)

array([nan,  0., nan,  0., nan,  0., nan])

In [6]:
arr[[0, 2]]

array([3, 2])

In [7]:
arr[[1, 0]]

array([8, 3])

In [8]:
arr[[True, True, True, False, False, True, False]]

array([3, 8, 2, 7])

In [9]:
np.where(arr == 5, 1, 0)

array([0, 0, 0, 0, 1, 0, 0])