In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [5]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
X = df.drop('species', axis=1)
y = df['species']

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
model = GaussianNB()

In [25]:
model.fit(X_train, y_train)

GaussianNB()

In [26]:
y_pred = model.predict(X_test)

In [27]:
from sklearn.metrics import classification_report

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [29]:
model.classes_

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [33]:
model.predict_proba(X_test)[0]

array([5.97327448e-90, 9.95635767e-01, 4.36423302e-03])

In [32]:
model.predict_log_proba(X_test)[0]

array([-2.05445363e+02, -4.37378408e-03, -5.43431282e+00])

In [34]:
model.class_prior_

array([0.33333333, 0.34166667, 0.325     ])