In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset('penguins')

In [4]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female


In [5]:
df['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [7]:
df.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
count,342.000000,342.000000,342.000000,342.000000
mean,43.921930,17.151170,200.915205,4201.754386
std,5.459584,1.974793,14.061714,801.954536
min,32.100000,13.100000,172.000000,2700.000000
25%,39.225000,15.600000,190.000000,3550.000000
50%,44.450000,17.300000,197.000000,4050.000000
75%,48.500000,18.700000,213.000000,4750.000000
max,59.600000,21.500000,231.000000,6300.000000


In [8]:
df['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [9]:
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [10]:
X = df.drop('species', axis=1)

In [11]:
y = df['species']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
X_train.head()

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
66,Biscoe,35.5,16.2,195.0,3350.0,Female
229,Biscoe,46.8,15.4,215.0,5150.0,Male
7,Torgersen,39.2,19.6,195.0,4675.0,Male
140,Dream,40.2,17.1,193.0,3400.0,Female
323,Biscoe,49.1,15.0,228.0,5500.0,Male


In [14]:
X_train.isna().sum()

island               0
bill_length_mm       1
bill_depth_mm        1
flipper_length_mm    1
body_mass_g          1
sex                  8
dtype: int64

In [15]:
X_train = X_train.dropna(subset='sex')

In [16]:
X_train.isna().sum()

island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [17]:
X_train.head()

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
66,Biscoe,35.5,16.2,195.0,3350.0,Female
229,Biscoe,46.8,15.4,215.0,5150.0,Male
7,Torgersen,39.2,19.6,195.0,4675.0,Male
140,Dream,40.2,17.1,193.0,3400.0,Female
323,Biscoe,49.1,15.0,228.0,5500.0,Male


In [18]:
y_train = y_train.loc[X_train.index]

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
ohe = OneHotEncoder(sparse_output=False, drop='first')

In [21]:
ohe.fit(X_train[['island', 'sex']])

OneHotEncoder(drop='first', sparse_output=False)

In [22]:
ohe.categories_

[array(['Biscoe', 'Dream', 'Torgersen'], dtype=object),
 array(['Female', 'Male'], dtype=object)]

In [23]:
ohe.get_feature_names_out()

array(['island_Dream', 'island_Torgersen', 'sex_Male'], dtype=object)

In [24]:
ohe.feature_names_in_

array(['island', 'sex'], dtype=object)

In [25]:
X_train[ohe.get_feature_names_out()] = ohe.transform(X_train[['island', 'sex']])

In [26]:
X_train = X_train.drop(['island', 'sex'], axis=1)

In [27]:
y_train

66        Adelie
229       Gentoo
7         Adelie
140       Adelie
323       Gentoo
         ...    
188    Chinstrap
71        Adelie
106       Adelie
270       Gentoo
102       Adelie
Name: species, Length: 267, dtype: object

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le = LabelEncoder()

In [30]:
y_train = le.fit_transform(y_train)

In [31]:
y_train

array([0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2, 0, 1, 1, 0, 0, 2, 0, 1,
       2, 2, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 0, 2, 0, 0,
       1, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 1, 2, 2, 2, 1, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0, 2, 1, 2, 1, 2,
       2, 2, 1, 2, 0, 0, 2, 2, 1, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 1, 2, 0,
       0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 1, 1, 0, 1, 2, 0, 2, 0, 2,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2, 1, 1, 0, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 0, 2, 2, 2, 0, 2, 1, 2, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 1, 2,
       2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 0, 2,
       0, 0, 2, 2, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 1, 1, 0, 0,
       2, 2, 0, 2, 1, 2, 1, 2, 2, 2, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 0,
       0, 2, 0])

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
model = LogisticRegression()

In [34]:
model.fit(X_train, y_train)

LogisticRegression()

In [35]:
X_test

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
194,Dream,50.9,19.1,196.0,3550.0,Male
157,Dream,45.2,17.8,198.0,3950.0,Female
225,Biscoe,46.5,13.5,210.0,4550.0,Female
208,Dream,45.2,16.6,191.0,3250.0,Female
318,Biscoe,48.4,14.4,203.0,4625.0,Female
...,...,...,...,...,...,...
321,Biscoe,55.9,17.0,228.0,5600.0,Male
172,Dream,42.4,17.3,181.0,3600.0,Female
73,Torgersen,45.8,18.9,197.0,4150.0,Male
76,Torgersen,40.9,16.8,191.0,3700.0,Female


In [36]:
X_test.isna().sum()

island               0
bill_length_mm       1
bill_depth_mm        1
flipper_length_mm    1
body_mass_g          1
sex                  3
dtype: int64

In [37]:
X_test = X_test.dropna(subset='sex')

In [38]:
X_test.isna().sum()

island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [39]:
y_test = y_test.loc[X_test.index]

In [40]:
X_test[ohe.get_feature_names_out()] = ohe.transform(X_test[['island', 'sex']])

In [41]:
X_test = X_test.drop(['island', 'sex'], axis=1)

In [42]:
y_test

194    Chinstrap
157    Chinstrap
225       Gentoo
208    Chinstrap
318       Gentoo
         ...    
321       Gentoo
172    Chinstrap
73        Adelie
76        Adelie
16        Adelie
Name: species, Length: 66, dtype: object

In [43]:
y_test = le.transform(y_test)

In [44]:
y_pred = model.predict(X_test)

In [45]:
y_pred

array([1, 1, 2, 1, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0,
       2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 0, 2,
       0, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 1, 2, 1, 0, 2, 0, 2, 1, 0, 0, 0])

In [46]:
y_proba = model.predict_proba(X_test)

In [47]:
y_proba

array([[1.40640310e-06, 9.99998593e-01, 3.39284947e-10],
       [4.08406198e-01, 5.86257704e-01, 5.33609801e-03],
       [1.00729189e-04, 3.14597364e-04, 9.99584673e-01],
       [3.11924438e-04, 9.99686248e-01, 1.82706598e-06],
       [4.91342485e-04, 6.92079891e-02, 9.30300668e-01],
       [4.66936449e-05, 1.04085446e-06, 9.99952266e-01],
       [9.57367451e-04, 2.91995481e-04, 9.98750637e-01],
       [6.09302607e-03, 6.34979272e-04, 9.93271995e-01],
       [9.99993777e-01, 3.04905792e-06, 3.17402926e-06],
       [6.60129664e-05, 1.47461901e-04, 9.99786525e-01],
       [2.80610366e-04, 1.29063839e-05, 9.99706483e-01],
       [9.99427651e-01, 5.68973309e-04, 3.37617253e-06],
       [9.99972025e-01, 2.35314372e-05, 4.44345049e-06],
       [9.99778273e-01, 3.23544822e-08, 2.21694911e-04],
       [3.69648382e-04, 2.65231616e-02, 9.73107190e-01],
       [9.97411981e-01, 3.29601956e-04, 2.25841686e-03],
       [9.65482054e-01, 7.11576626e-06, 3.45108300e-02],
       [1.56683264e-05, 1.36398

In [48]:
model.classes_

array([0, 1, 2])

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report, log_loss

In [50]:
print(confusion_matrix(y_test, y_pred))

[[30  0  0]
 [ 0 16  0]
 [ 0  0 20]]


In [51]:
accuracy_score(y_test, y_pred)

1.0

In [52]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        20

    accuracy                           1.00        66
   macro avg       1.00      1.00      1.00        66
weighted avg       1.00      1.00      1.00        66



In [53]:
model.score(X_train, y_train)

0.9850187265917603

In [54]:
model.score(X_test, y_test)

1.0

In [55]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[['bill_length_mm',
         'bill_depth_mm',
         'flipper_length_mm',
         'body_mass_g']] = scaler.fit_transform(
    X_train[['bill_length_mm',
             'bill_depth_mm',
             'flipper_length_mm',
             'body_mass_g']]
)

X_test[['bill_length_mm',
        'bill_depth_mm',
        'flipper_length_mm',
        'body_mass_g']] = scaler.transform(
    X_test[['bill_length_mm',
            'bill_depth_mm',
            'flipper_length_mm',
            'body_mass_g']]
)

In [56]:
model2 = LogisticRegression()

In [57]:
model2.fit(X_train, y_train)

LogisticRegression()

In [58]:
y_pred = model2.predict(X_test)

In [59]:
y_proba = model2.predict_proba(X_test)

In [60]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98        30
           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00        20

    accuracy                           0.98        66
   macro avg       0.99      0.98      0.98        66
weighted avg       0.99      0.98      0.98        66

